# Generated by Django 4.2.4 on 2023-09-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvsp', '0002_alter_confirmacao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacao',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
